<?php
/**
 * Created by PhpStorm.
 * User: cxx
 * Date: 2018/1/28
 * Time: 14:56
 */
class emailException extends exception{

}
class pwdException extends exception{
    function __toString()
    {

        return $this->getCode().PHP_EOL.$this->getMessage().PHP_EOL.$this->getFile().PHP_EOL.$this->getLine();
        //parent::__toString(); // TODO: Change the autogenerated stub
        //echo 123;
    }
}

function reg ($reginfo = null){
    if(empty($reginfo) || !isset($reginfo)){
        throw new Exception("参数非法");
    }
    if(empty($reginfo['email'])){
        throw new emailException("邮件为空");
    }
    if($reginfo['pwd'] != $reginfo['repwd']){
        throw new pwdException("两次密码不一致");
    }
    echo "success";
}

try{
    reg(array('email'=>'aa@qq.com','pwd'=>123456,'repwd'=>12345678));

}catch (emailException $ee){
    echo $ee->getMessage();
}catch (pwdException $ep){
    echo $ep;
    echo PHP_EOL,'teshuchuli';
}catch (Exception $e){
    echo $e->getTraceAsString();
    echo PHP_EOL,'qitaqingkuang';
}
